### ISSUE TITLE
Hive local install cannot get past signup

### ISSUE THREAD

**Issue by RedCloudDC** [graphql-hive/platform#5188]
I was able to local install Hive on RHEL (docker compose) and create an account on the website, however, I cannot get the sign-on (or) sign-up to work. also I can only access the Hive app on remote desktop and not my local machine on same network even though docker port is listening on 0:0:0:0

**Comment by dotansimha** [comment]
@RedCloudDC Please share more info and I'll re-open. We need logs and additional information to understand if something is wrong, or configured incorrectly. 
Thanks
