### ISSUE TITLE
Feedback for “Hive CLI (Command Line Interface)”

### ISSUE THREAD

**Issue by Wallman** [graphql-hive/platform#5615]
Feedback on https://the-guild.dev/graphql/hive/docs/api-reference/cli

If `/usr/local/lib` does not exist (which it didn't for me or any of my colleagues) then `curl -sSL https://graphql-hive.com/install.sh | sh` fails silently.

We solved it with
```
cd /usr/local
sudo mkdir lib
```

but this should be improved.

**Comment by saihaj** [comment]
what OS was this on?

**Comment by Wallman** [comment]
> what OS was this on?

macOS Sonoma

**Comment by dotansimha** [comment]
Duplicate of https://github.com/graphql-hive/platform/issues/3292
