### ISSUE TITLE
Bug: Hive does not label removing enum values as unsafe

### ISSUE THREAD

**Issue by klys-equinix** [graphql-hive/platform#5659]
Hive is not marking removing (or adding) values from enum as unsafe changes.
Here are relevant examples:
If we rename an enum, that is marked as unsafe change, and that clients will be affected - correctly:
https://app.graphql-hive.com/equinix/vdc/dev/checks/764e4697-db61-4d79-9fa6-90d7a707ed9a?filter_changed=false&filter_failed=false
But if we remove values from that enum, that shows as safe:
https://app.graphql-hive.com/equinix/vdc/dev/checks/391bfc25-db46-4ac8-8788-0847f439cb37?filter_changed=false&filter_failed=false
But both of those changes are similarly disruptive

Check 1:
<img width="1348" alt="Screenshot 2024-10-10 at 07 13 55" src="https://github.com/user-attachments/assets/143c359d-aba2-4096-b7c3-a89adcce44f5">
Check 2:
<img width="1340" alt="Screenshot 2024-10-10 at 07 14 16" src="https://github.com/user-attachments/assets/9479cea1-b95b-4d10-9c3c-12a6892acc94">

**Comment by kamilkisiela** [comment]
#5667
