### ISSUE TITLE
Unexpected Composition Error due to Interface Being Interpreted as a Type

### ISSUE THREAD

**Issue by jenskm** [graphql-hive/platform#5869]
Hello

While integrating a new subgraph into our project, we encountered composition errors due to the subgraph schema's incompatibility with our two previously published subgraphs. This was an expected issue. However, an unexpected error arose, causing the only output received from `schema:check` to be "Unexpected composition error." All the specific errors due to supergraph composition were hidden.

When we ran the project with `hive dev`, we got a more descriptive error message: "Error: Expected interface, got object." The issue seems to occur when composing schemas where an entity is used as a Type in subgraph A and an Interface in subgraph B. If another type implements this interface, it is then presumed to be a type instead of an interface. 

Here's a minimal example to reproduce the error:

**cars.graphql**
```graphql
type Query {
  foo(id: ID!): String
}

interface Vehicle {
    id: ID!
}

type Car implements Vehicle {
  id: ID!
}
```

**vehicles.graphql**
```graphql
type Vehicle {
    id: ID!
}
```

Command used: 
```bash
hive dev \                               
  --service cars --url http://localhost:8080/graphql --schema cars.graphql \
  --service vehicles --url https://localhost:9090/graphql --schema vehicles.graphql
```

This results in the output: "Error: Expected interface, got object."

For reference, Apollo Rover outputs: 
```
Caused by:
TYPE_KIND_MISMATCH: Type "Vehicle" has mismatched kind: it is defined as Interface Type in subgraph "cars" but Object Type in subgraph "vehicles"
INVALID_FIELD_SHARING: Non-shareable field "Car.id" is resolved from multiple subgraphs: it is resolved from subgraphs "cars" and "vehicles" (through @interfaceObject field "Vehicle.id") and defined as non-shareable in subgraph "cars"
```

I guess this is a bug?

**Comment by kamilkisiela** [comment]
Fixed on its way!

**Comment by kamilkisiela** [comment]
https://github.com/the-guild-org/federation/pull/74

**Comment by kamilkisiela** [comment]
@jenskm it should be in production in about 20 minutes
