### ISSUE TITLE
404 error on changelog for self-hosting

### ISSUE THREAD

**Issue by yanns** [graphql-hive/platform#5895]
The [README](https://github.com/graphql-hive/platform/blob/main/README.md) file has a link to [View the changelog for self-hosting](https://github.com/graphql-hive/platform/blob/main/deployments/CHANGELOG.md), but this link does not work.

**Comment by n1ru4l** [comment]
This is the correct file: https://github.com/graphql-hive/platform/blob/main/deployment/CHANGELOG.md

**Comment by yanns** [comment]
thanks, I'll open a PR for the readme file.

**Comment by n1ru4l** [comment]
Already fixed @yanns https://github.com/graphql-hive/platform/commit/5c4b7ddffa44803d7712989ca70786df3a417a46

**Comment by yanns** [comment]
amazing! 😍
